### ISSUE TITLE
Can't login via spotify after installation.

### ISSUE THREAD

**Issue by hamx01** [apricote/Listory#263]
Hi! I'm installed Listory on docker. With the docker compose, I edited the .env and entered client_id and secret. I'm built application and opened localhost 3000. But there is nothing except Log In button and this button is not working. I would be very grateful for your help.

**Comment by apricote** [comment]
Hey @hamx01!

Great to hear you want to run Listory yourself, sorry that its not really well documented right now, you are the first to try so.

I think there are two problems:

1. The `docker-compose.yml` is built for development purposes, it is way more complicated and slower than what it could be for "production". I will work on a new production `docker-compose` in the coming days.

2. You need to tell Spotify in the [Spotify Developer Dashboard](https://developer.spotify.com/dashboard) what URLs are allowed to login/callback. If you run Listory on your local computer with the development `docker-compose.yml` setup, the URL is probably `http://localhost:3000/api/v1/auth/spotify/callback`, but if you are hosting this on a server with a proper DNS name & certificate, the URL might be `https://listory.hamx01.com/api/v1/auth/spotify/callback`. You can change this by clicking "Edit Settings" in the dashboard for your app.

After you have added the callback URL to your Spotify App, if its still not working, could you send me the logs from the `api` container during the time you try to login?

**Comment by hamx01** [comment]
Okay, I edited the docker-compose.yml and .releaserc.yml. 
In the Spotify dashboard, I pasted the link as you wrote. (I have my domain with DNS pointed to it properly and valid certificates)
And after that tried to run it. And...
1. I tried to start it on my ARM64 VPS, and your API image does not support this architecture.
2. After I run it under AMD64, it was ok. 
3. When I tried to Log In, the _blank page is opened and there is only one message: 
![изображение](https://user-images.githubusercontent.com/101278038/227633408-398cec41-1dbf-42c8-97ee-7f1051e32e9f.png)
4. There are some logs as you wished
[listory-api-1_logs.txt](https://github.com/apricote/Listory/files/11066427/listory-api-1_logs.txt)

**Comment by hamx01** [comment]
Hi @apricote ,
Have you checked the logs?

**Comment by apricote** [comment]
> Hi @apricote , Have you checked the logs?

Sorry for the late response. I took a look at it and something is weird about the logs, for example this line:

> 55197/04/02 02:20PM INF undefined | pid=1 hostname=7204707e7954 reqId=45 req=[object Object] res=[object Object] responseTime=0 msg=request completed 

Only contains `[object Object]` for the request and response objects, but those would have the interesting data. I have a hard time understand how the logs get formatted this way. What image are you using and do you set the environment variable `NODE_ENV` in `docker-compose.yml` or `.env`?

As for the redirect issue, did you set `APP_URL` equal to the (base) URL where you are hosting listory? If this does not match, you might get an invalid redirect. You can check the Redirect URL that Listory sets by running `curl localhost:3000/api/v1/auth/spotify -v` (replace `localhost:3000` with your domain). The response will contain the following Header, which in turn includes the redirect URL that Listory sends to Spotify and that must match what you have configured in the Spotify Dashboard. Note that the Redirect URL is URL encoded in the following line:

```
< Location: https://accounts.spotify.com/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fapi%2Fv1%2Fauth%2Fspotify%2Fcallback&scope=user-read-private%20user-read-email%20user-read-recently-played&client_id=MY_CLIENT_ID
```

> I tried to start it on my ARM64 VPS, and your API image does not support this architecture.

I have just opened #265 to add ARM images to the release pipeline :)

**Comment by apricote** [comment]
Version 1.24.2 now also has an arm image 😊

**Comment by hamx01** [comment]
I was using this image: apricote/listory:1.23.3
No i don't set NODE_ENV, because you don't have it in your .env.sample and in your docker-compose.prod.yml file.
Yep i set proper `APP_URL` and checked it. I will try one more time, now on my ARM64 VPS, with your new image.

**Comment by hamx01** [comment]
Okay, now after i enter my `SPOTIFY_CLIENT_ID` and `SPOTIFY_CLIENT_SECRET`, also edited `APP_URL` variable, it is working great.
Thank you so much for your help!

**Comment by apricote** [comment]
Wonderful :) Glad to hear it working for you.
